name: wise_repeat
description: "A wise way to learn new words from foreign language"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.0.1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  bloc: ^8.1.4
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  meta: ^1.11.0
  json_serializable: ^6.8.0
  path_provider: ^2.0.15
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true
